name: CI

on:
  push:
    branches:
      - master
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start
      run: echo Running Build# $GITHUB_RUN_NUMBER on Branch $GITHUB_REF
    - name: Install Dependencies
      run: npm install
    - name: Install Dependencies
      run: npm install
    - name: Run Unit Tests
      run: npm run test
    - name: Linting the code
      run: npm run lint
    - name: Build the solution
      run: npm run predeploy -- $GITHUB_RUN_NUMBER
    - name: Deploy
      env:
        FIREBASETOKEN: ${{ secrets.FIREBASETOKEN }}
      run: firebase deploy --token $FIREBASETOKEN --only hosting,functions
      if: github.ref == 'release'
